name: Dynatrace Integration

on:
  push:
    branches:
      - main  # Customize according to your branch.

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Dynatrace Event
        run: |
          
          # Replace <YOUR_DYNATRACE_TENANT> with your Dynatrace tenant URL
          # Replace <YOUR_DYNATRACE_API_TOKEN_SECRET> with the name of your GitHub secret
          # Customize the event payload as needed
          curl -X POST "https://wnx02121.live.dynatrace.com/api/v2/events" \
          -H "Authorization: Api-Token ${{ secrets.DYNA_API }}" \
          -H "Content-Type: application/json" \
          -d '{
                "eventType": "CUSTOM_EVENT",
                "eventName": "Deployment",
                "description": "GitHub Actions Deployment",
                "customProperties": {
                  "branch": "${{ github.ref }}",
                  "commit": "${{ github.sha }}"
                }
              }'
