name: Dyna-actions
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      run: this-will-fail
    - name: Notify Dynatrace on Build Failed
      if: failure()
      uses: dynatrace-oss/dynatrace-github-action@v9
      with:
        url: '${{ secrets.DT_URL }}'
        token: '${{ secrets.NEW_DYNA_TOK }}'
        events: |
          - title: "Build failed"
            type: CUSTOM_INFO
            entitySelector: type(host),entityName(myHost)
            properties:
              description: "Branch ${{ github.ref }} failed to build"
              source: GitHub
              project: "${{ github.repository }}"
              branch: "${{ github.ref }}"
              event: "${{ github.event_name }}"
              owner: ${{ github.repository_owner }}
