- name: Build count
  uses: dynatrace-oss/dynatrace-github-action@v9
  with:
    url: '${{ secrets.DT_URL }}'
    token: '${{ secrets.DT_API_TOKEN }}'
    metrics: |
      - metric: "github.metric1"
        value: "1.0"
        dimensions:
          project: "${{ github.repository }}"
          branch: "${{ github.ref }}"
          event: "${{ github.event_name }}"
          owner: wolfgang
