name: Jira Integration
on: workflow_dispatch
#  push: 
#    branches:
 #     - main
jobs:
  jira_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: Sync with Jira
        run: |
          # Your Jira integration code here
          # You can use Jira REST API or libraries like "jira-client" to interact with Jira.
          # Example: npm run sync-jira
        env:
          JIRA_UID: ${{ secrets.JIRA_UID }}
          JIRA_API:  ${{ secrets.JIRA_API }}
