name: Sysdig Secure Scan

on:
  push:
    branches:
      - main  # Customize this to the branch you want to trigger the scan on...

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sysdig Secure Inline Scan
      uses: sysdiglabs/scan-action@v3.5.0
      with:
        image-name: "your-container-image:tag"  # Specify the image you want to scan
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}

