name: thirdworkflow
on: workflow_dispatch 
jobs:
  Deploy-to-Dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: deploy
        run: yumt install py
  Deploy-to-Prod:
    runs-on: ubuntu-latest
    steps:
      - name: deploy2
        run: yum install apach
